### ISSUE TITLE
run with error, can you help me , please.

### ISSUE THREAD

**Issue by dddaiwstep** [kendrick0907/lihkg_news#1]
When i run the py file , i got the following error:

Traceback (most recent call last):
  File "C:\Users\lau\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 97, in start
    path = SeleniumManager().driver_location(browser)
  File "C:\Users\lau\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\selenium_manager.py", line 74, in driver_location
    result = self.run((binary, flag, browser))
  File "C:\Users\lau\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\selenium_manager.py", line 93, in run
    raise SeleniumManagerException(f"Selenium manager failed for: {command}. {stderr}")
selenium.common.exceptions.SeleniumManagerException: Message: Selenium manager failed for: C:\Users\lau\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\windows\selenium-manager.exe --browser chrome. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\lau\AppData\Local\Programs\Python\Python310\Scripts\lihkg_news.py", line 17, in <module>
    driver = Chrome(options=chrome_options)
  File "C:\Users\lau\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 81, in __init__
    super().__init__(
  File "C:\Users\lau\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 103, in __init__
    self.service.start()
  File "C:\Users\lau\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 100, in start
    raise err
  File "C:\Users\lau\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 90, in start
    self._start_process(self.path)
  File "C:\Users\lau\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 213, in _start_process
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://chromedriver.chromium.org/home

Can you help me ? 
Thanks.

**Comment by kendrick0907** [comment]
Hi dddaiwstep,

Thanks for raising the question! 

Do you use Google Chrome in your PC normally? It seems like the chrome driver (i.e. the Google Chrome) is not installed appropriately. 
You can try installing any latest version of the google chrome driver:
https://chromedriver.chromium.org/downloads/version-selection

If you do not have Google Chrome, you could try install the most common version, which you can easily find on the internet. 

[image of google chrome]
<img width="76" alt="Screenshot 2024-02-22 at 9 50 08 AM" src="https://github.com/kendrick0907/lihkg_news/assets/65549544/1de0feb2-6b84-495e-b25d-5cdfca40f62d">

Kendrick

**Comment by dddaiwstep** [comment]
Thanks for your assistance. 

I can open the chrome with url "https://lihkg.com/category/5?order=hot" now, but the question is
"How can i scrape the data and save it in a csv file? "

Thanks for your help again .

**Comment by kendrick0907** [comment]
The code can scrape the title of the trending news on LIHKG now and stores the results into lists(title_ls and url_ls). 
If you want to export the data to csv file. You may need some knowledge in using a Python Library called "Pandas", and create "DataFrames" which is a datatype under Pandas. After that, you can use the built-in Python function ".to_csv()" to make a csv file. You can take reference from the last few line of codes from my another LIHKG scrapping project which exports comments in any LIHKG post into csv. https://github.com/kendrick0907/LIHKG-Scrapping  

However, if you would also like to have a simple solution to see the result. You can simply try print the lists like adding print(title_ls) and print(url_ls) in the end of the code. 

By the way, as you are the first person making a comment in my projects, may I know the reason why you are interested in this project? Your response can help me better prepare for other projects :)! 

Kendrick
